timezone: America/Detroit

domain: mclaysen.com
email_address: me@mclaysen.com
username: mclaysen
node_exporter_version: 1.10.2
cadvisor_listen_ip: 172.17.0.1
cadvisor_port: 8080
cadvisor_version: 0.55.1

# Pangolin installer configuration
reverse_proxy_ip: 192.168.86.168

unifi_url: https://192.168.86.1

docker_metrics_addr: 0.0.0.0:9323

# Portainer configuration
portainer_image: portainer/portainer-ce
portainer_tag: 2.41.1
portainer_container_name: portainer
portainer_data_dir: /opt/portainer/data
portainer_https_port: 9443
portainer_agent_port: 9001
portainer_http_port: 9000
endpoint_id: 3
portainer_manager_endpoint: http://192.168.86.202:9000 #https://container-manager.mclaysen.com

#Cloudflared configuration
cloudflared_version: 2026.5.0

# Newt configuration
newt_version: 1.8.1
blueprint_file_path: /home/{{ username }}/docker/newt/config/home1_pangolin_blueprint.yml

#Jellyfin
jellyfin_version: 10.11.8

ansible_user_name: ansible
ansible_user_ssh_public_key_path: ~/.ssh/container-manager.pub

sudoers_file_path: /etc/sudoers

security_ssh_config_path: /etc/ssh/sshd_config
security_sshd_name: sshd

security_ssh_port: 22
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "no"
security_sshd_state: started
security_ssh_restart_handler_state: restarted
security_ssh_allowed_users: 
  - "{{ ansible_user_name }}"
security_ssh_allowed_groups: []

security_sudoers_passwordless:
  - "{{ ansible_user_name }}"
security_sudoers_passworded: []

security_autoupdate_enabled: true
security_autoupdate_blacklist: []
security_autoupdate_additional_origins: []
