---
- name: Config home server
  hosts: home_server
  become: true
  vars_files:
    - group_vars/home_server/vars.yml
    - group_vars/home_server/vault.yml
  handlers:
    - ansible.builtin.import_tasks: shared/handlers/main.yml
  tasks:
    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
        allowerasing: true

    - name: Install basic tools
      ansible.builtin.dnf:
        name:
          - nano
          - usbutils
        state: present

    - name: Set timezone
      community.general.timezone:
        name: "{{ timezone }}"

    - name: Setup cockpit
      ansible.builtin.import_tasks: home-server/tasks/setup_cockpit.yml

    - name: Setup libvirt
      ansible.builtin.import_tasks: home-server/tasks/initialize_libvirt.yml

    - name: Initialize VM bridge
      ansible.builtin.import_tasks: home-server/tasks/intialize_bridge.yml

    - name: Create home assistant vm
      ansible.builtin.import_tasks: home-server/tasks/create_home_assistant.yml