---
- name: Config home server
  hosts: home_server
  become: true
  vars_files:
    - group_vars/home_server/vars.yml
  handlers:
    - ansible.builtin.import_tasks: shared/handlers/main.yml
  tasks:
    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true

    - name: Setup users
      ansible.builtin.import_tasks: home-server/tasks/user.yml
    
    - name: Setup SSH
      ansible.builtin.import_tasks: shared/tasks/ssh.yml

    - name: Setup monitoring apps on host
      ansible.builtin.import_tasks: home-server/tasks/apps.yml
    
    - name: Install Docker
      ansible.builtin.import_tasks: shared/tasks/docker.yml
      vars:
        deploy_user_name: "{{ deploy_user_name }}"
  