---
- name: Manage Portainer stacks
  hosts: portainer_managers
  gather_facts: false
  collections:
    - bgtor.portainer
  vars_files:
    - group_vars/portainer_managers/vault.yml
  vars:
    portainer_url: "https://container-manager.mclaysen.com"
    portainer_token: "{{ portainer_api_token }}"
    endpoint_id: 1
    rendered_dir: "/tmp/portainer-stacks"
    stacks:
      - name: jellyfin
        template: stacks/jellyfin.yml.j2
        stack_type: standalone
        endpoint_id: 3
        env: []
        prune: true
        pull_images: true
      - name: jellystat
        template: stacks/jellystat.yml.j2
        stack_type: standalone
        endpoint_id: 3
        env: []
        prune: true
        pull_images: true
  tasks:
    - name: Ensure API token is provided
      ansible.builtin.assert:
        that: portainer_token != ""
        fail_msg: "PORTAINER_API_TOKEN environment variable must be set"

    - name: Ensure rendered compose directory exists
      ansible.builtin.file:
        path: "{{ rendered_dir }}"
        state: directory
        mode: "0700"
      delegate_to: localhost
      become: false
      run_once: true

    - name: Render compose templates for stacks
      ansible.builtin.template:
        src: "{{ item.template }}"
        dest: "{{ rendered_dir }}/{{ item.name }}.yml"
      loop: "{{ stacks | selectattr('template', 'defined') | list }}"
      loop_control:
        label: "{{ item.name }}"
      no_log: true
      delegate_to: localhost
      become: false
      run_once: true

    - name: Deploy or update Portainer stacks from compose files
      bgtor.portainer.portainer_stack:
        portainer_url: "{{ portainer_url }}"
        portainer_token: "{{ portainer_token }}"
        name: "{{ item.name }}"
        stack_type: "{{ item.stack_type | default('standalone') }}"
        stack_source: file
        endpoint_id: "{{ item.endpoint_id | default(endpoint_id) }}"
        file: "{{ (item.template is defined) | ternary(rendered_dir ~ '/' ~ item.name ~ '.yml', item.file) }}"
        env: "{{ item.env | default([]) }}"
        prune: "{{ item.prune | default(true) }}"
        pull_images: "{{ item.pull_images | default(false) }}"
        timeout: 300
        state: present
      loop: "{{ stacks }}"
      loop_control:
        label: "{{ item.name }}"
      delegate_to: localhost
      become: false
      run_once: true

    - name: Clean up rendered compose files
      ansible.builtin.file:
        path: "{{ rendered_dir }}/{{ item.name }}.yml"
        state: absent
      loop: "{{ stacks | selectattr('template', 'defined') | list }}"
      loop_control:
        label: "{{ item.name }}"
      delegate_to: localhost
      become: false
      run_once: true
