---
- name: Prepare Stack Configurations
  hosts: container_manager
  become: true
  handlers:
    - ansible.builtin.import_tasks: container-manager/handlers/main.yml
  vars_files:
    - group_vars/portainer_managers/vars.yml
  tasks:
    - name: Create monitoring config directory
      ansible.builtin.file:
        path: "/home/{{ username }}/docker/monitoring/prometheus"
        state: directory
        mode: '0755'
        recurse: true

    - name: Place Prometheus configuration
      ansible.builtin.template:
        src: stacks/prometheus_config.yml.j2
        dest: "/home/{{ username }}/docker/monitoring/prometheus/prometheus.yml"
        mode: '0644'

    - name: Deploy docker config
      ansible.builtin.template:
        src: container-manager/templates/docker_daemon.json.j2
        dest: /etc/docker/daemon.json
      notify: restart docker

    - name: Deploy monitoring apps
      ansible.builtin.import_tasks: container-manager/tasks/apps.yml

- name: Manage Portainer stacks
  hosts: portainer_managers
  gather_facts: false
  collections:
    - bgtor.portainer
  vars_files:
    - group_vars/portainer_managers/vault.yml
  vars:
    portainer_url: https://container-manager.mclaysen.com
    portainer_token: "{{ portainer_api_token }}"
    endpoint_id: 3
    rendered_dir: /tmp/portainer-stacks
    stacks:
      - name: monitoring_stack
        template: stacks/monitoring_stack.yml.j2
        stack_type: standalone
        endpoint_id: 3
        env: []
        prune: true
        pull_images: true
      - name: jellyfin
        template: stacks/jellyfin.yml.j2
        stack_type: standalone
        endpoint_id: 3
        env: []
        prune: true
        pull_images: true
      - name: jellystat
        template: stacks/jellystat.yml.j2
        stack_type: standalone
        endpoint_id: 3
        env: []
        prune: true
        pull_images: true
      - name: newt
        template: stacks/newt.yml.j2
        stack_type: standalone
        endpoint_id: 3
        env: []
        prune: true
        pull_images: true
      - name: cloudflared
        template: stacks/cloudflared.yml.j2
        stack_type: standalone
        endpoint_id: 3
        env: []
        prune: true
        pull_images: true
  tasks:
    - name: Ensure API token is provided
      ansible.builtin.assert:
        that: portainer_token != ""
        fail_msg: PORTAINER_API_TOKEN environment variable must be set

    - name: Ensure rendered compose directory exists
      ansible.builtin.file:
        path: "{{ rendered_dir }}"
        state: directory
        mode: "0700"
      delegate_to: localhost
      become: false
      run_once: true

    - name: Render compose templates for stacks
      ansible.builtin.template:
        src: "{{ item.template }}"
        dest: "{{ rendered_dir }}/{{ item.name }}.yml"
      loop: "{{ stacks | selectattr('template', 'defined') | list }}"
      loop_control:
        label: "{{ item.name }}"
      no_log: true
      delegate_to: localhost
      become: false
      run_once: true

    - name: Create network for Pangolin
      bgtor.portainer.portainer_network:
        portainer_url: "{{ portainer_url }}"
        portainer_token: "{{ portainer_token }}"
        name: pangolin_network
        driver: bridge
        endpoint_id: "{{ endpoint_id }}"
        state: present
        internal: false
      delegate_to: localhost
      become: false
      run_once: true

    - name: Deploy or update Portainer stacks from compose files
      bgtor.portainer.portainer_stack:
        portainer_url: "{{ portainer_url }}"
        portainer_token: "{{ portainer_token }}"
        name: "{{ item.name }}"
        stack_type: "{{ item.stack_type | default('standalone') }}"
        stack_source: file
        endpoint_id: "{{ item.endpoint_id | default(endpoint_id) }}"
        file: "{{ (item.template is defined) | ternary(rendered_dir ~ '/' ~ item.name ~ '.yml', item.file) }}"
        env: "{{ item.env | default([]) }}"
        prune: "{{ item.prune | default(true) }}"
        pull_images: "{{ item.pull_images | default(false) }}"
        timeout: 300
        state: present
      loop: "{{ stacks }}"
      loop_control:
        label: "{{ item.name }}"
      delegate_to: localhost
      become: false
      run_once: true

    - name: Clean up rendered compose files
      ansible.builtin.file:
        path: "{{ rendered_dir }}/{{ item.name }}.yml"
        state: absent
      loop: "{{ stacks | selectattr('template', 'defined') | list }}"
      loop_control:
        label: "{{ item.name }}"
      delegate_to: localhost
      become: false
      run_once: true