---
- name: Setup and configure proxy server
  hosts: proxy_hosts_test
  become: true
  vars_files:
    - group_vars/proxy_hosts/vars.yml
  handlers:
    - ansible.builtin.import_tasks: shared/handlers/main.yml
  tasks:
    - name: Update all packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: true

    - name: Set timezone
      community.general.timezone:
        name: "{{ timezone }}"
      
    - name: Configure SSH security
      ansible.builtin.import_tasks: shared/tasks/ssh.yml

    - name: Set 644 for the authorized_keys file
      ansible.builtin.file:
        path: "/home/{{ username }}/.ssh/authorized_keys"
        mode: '0644'