---
- name: Setup and configure proxy server
  hosts: proxy_hosts
  become: true
  vars_files:
    - group_vars/proxy_hosts/vars.yml
    - group_vars/proxy_hosts/vault.yml
  handlers:
    - ansible.builtin.import_tasks: shared/handlers/main.yml
    - ansible.builtin.import_tasks: proxy/handlers/main.yml
  tasks:
    - name: Update all packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: true

    - name: Install basic tools
      ansible.builtin.apt:
        name:
          - certbot
          - python3-certbot-dns-cloudflare
        state: present

    - name: Set timezone
      community.general.timezone:
        name: "{{ timezone }}"
      
    - name: Configure SSH security
      ansible.builtin.import_tasks: shared/tasks/ssh.yml

    - name: Set 644 for the authorized_keys file
      ansible.builtin.file:
        path: "/home/{{ username }}/.ssh/authorized_keys"
        mode: '0644'

    - name: Install NGINX
      ansible.builtin.include_role:
        name: nginxinc.nginx
      vars:
        nginx_branch: stable

    - name: Setup certbot
      ansible.builtin.import_tasks: proxy/tasks/certbot_conf.yml

    - name: Configure NGINX
      ansible.builtin.import_tasks: proxy/tasks/nginx_conf.yml

    - name: Configure NGINX sites
      ansible.builtin.import_tasks: proxy/tasks/nginx_set_sites.yml