---
roles:
  - name: geerlingguy.node_exporter
  - name: nginxinc.nginx
collections:
  - name: bgtor.portainer
  - name: community.docker
  - name: community.general
  - name: prometheus.prometheus
  - name: grafana.grafana
  - name: nginxinc.nginx_core
    version: 0.8.0
  - name: community.libvirt
    version: 2.2.0