---
- name: restart docker
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Restart newt
  community.docker.docker_container:
    name: newt
    state: started
    restart: true