---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart ssh
  ansible.builtin.service:
    name: "{{ security_sshd_name }}"
    state: "{{ security_ssh_restart_handler_state }}"

- name: restart supervisor
  ansible.builtin.service:
    name: supervisor
    state: restarted

- name: reload udev rules
  ansible.builtin.command: udevadm control --reload-rules

- name: trigger udev rules
  ansible.builtin.command: udevadm trigger --subsystem-match=usb

- name: restart mqtt supervisor program
  community.general.supervisorctl:
    name: mqtt
    state: restarted