deploy_user_name: ansible
user_name: "{{ deploy_user_name }}"
deployuser_ssh_public_key_path: ~/.ssh/home-server.pub

timezone: America/Detroit

libvirt_storage_pools:
  - name: fast
    path: /var/lib/libvirt/images-fast
  - name: bulk
    path: /var/lib/libvirt/images-bulk

# General vm configs
vm_images_cache_dir: /var/cache/libvirt/images
vm_pool_name_fast: fast
vm_pool_name_bulk: bulk
vm_network_bridge_name: vm-bridge

# Home assistant vm configs
home_assistant_base_image: https://github.com/home-assistant/operating-system/releases/download/17.3/haos_ova-17.3.qcow2.xz
home_assistant_base_image_checksum: sha256:d42fadf806c0690792a4460ff3a72c2846c4e16e2033aefad0835662e7a9696f
home_assistant_disk_path: /var/lib/libvirt/images-fast/home-assistant.qcow2
home_assistant_usb_host_device: usb_1_6

# Bridge network configuration
bridge_network_name: br0
bridge_interface_name: br0-slave-enp4s0
ethernet_ifname: enp4s0


#monitoring configs
cadvisor_listen_ip: 172.17.0.1
cadvisor_port: 8080
cadvisor_version: 0.55.1
node_exporter_version: 1.10.2

sudoers_file_path: /etc/sudoers.d/ansible-file

security_ssh_config_path: /etc/ssh/sshd_config
security_sshd_name: sshd

security_ssh_port: 22
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "yes"
security_sshd_state: started
security_ssh_restart_handler_state: restarted
security_ssh_allowed_users: 
  - "{{ user_name }}"
security_ssh_allowed_groups: []

security_sudoers_passwordless:
  - "{{ user_name }}"
security_sudoers_passworded: []

security_autoupdate_enabled: true
security_autoupdate_blacklist: []
security_autoupdate_additional_origins: []