---
- name: Ensure VM image cache directory exists
  ansible.builtin.file:
    path: "{{ vm_images_cache_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags:
    - reverse_proxy_vm

- name: Gather defined VMs
  community.libvirt.virt:
    command: list_vms
  register: defined_vms
  tags:
    - reverse_proxy_vm

- name: Check if the disk for the reverse proxy VM already exists
  ansible.builtin.stat:
    path: "{{ reverse_proxy_disk_path }}"
  register: reverse_proxy_disk
  tags:
    - reverse_proxy_vm

- name: Download the Ubuntu cloud image
  ansible.builtin.get_url:
    url: "{{ reverse_proxy_base_image }}"
    dest: "{{ vm_images_cache_dir }}/{{ reverse_proxy_seed_img_name }}"
    checksum: "{{ reverse_proxy_base_image_checksum }}"
    mode: "0644"
  when: not reverse_proxy_disk.stat.exists
  tags:
    - reverse_proxy_vm

- name: Copy the reverse proxy image to disk path
  ansible.builtin.copy:
    src: "{{ vm_images_cache_dir }}/{{ reverse_proxy_seed_img_name }}"
    dest: "{{ reverse_proxy_disk_path }}"
    remote_src: true
    mode: "0644"
  when: not reverse_proxy_disk.stat.exists
  tags:
    - reverse_proxy_vm

- name: Extract the reverse proxy seed user data
  ansible.builtin.template:
    src: home-server/templates/reverse_proxy_seed.yml.j2
    dest: "{{ vm_images_cache_dir }}/{{ reverse_proxy_seed_user_name }}"
    mode: "0644"
  tags:
    - reverse_proxy_vm

- name: Extract the reverse proxy seed meta image
  ansible.builtin.template:
    src: home-server/templates/reverse_proxy_meta.yml.j2
    dest: "{{ vm_images_cache_dir }}/{{ reverse_proxy_seed_meta_name }}"
    mode: "0644"
  tags:
    - reverse_proxy_vm

- name: Create cloud-init ISO for reverse proxy
  ansible.builtin.command:
    cmd: >-
      genisoimage -output {{ reverse_proxy_seed_img_path }} -volid cidata -joliet -rock -graft-points
      user-data={{ vm_images_cache_dir }}/{{ reverse_proxy_seed_user_name }}
      meta-data={{ vm_images_cache_dir }}/{{ reverse_proxy_seed_meta_name }}
  tags:
    - reverse_proxy_vm

- name: Resize the reverse proxy image
  ansible.builtin.command:
    cmd: >-
      qemu-img resize {{ reverse_proxy_disk_path }} {{ reverse_proxy_disk_size_gb | int }}G
  when: not reverse_proxy_disk.stat.exists
  tags:
    - reverse_proxy_vm

- name: Create or update reverse proxy VM
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'home-server/templates/reverse_proxy_domain.xml.j2') }}"
    autostart: true
    mutate_flags:
      - ADD_UUID
  tags:
    - reverse_proxy_vm

- name: Set the running vms
  community.libvirt.virt:
    command: list_vms
    state: running
  register: running_vms
  tags: 
    - reverse_proxy_vm

- name: Ensure reverse proxy vm is running
  community.libvirt.virt:
    name: "{{ reverse_proxy_vm_name }}"
    state: running
  when: reverse_proxy_vm_name not in (running_vms.list_vms | default([]))
  tags:
    - reverse_proxy_vm
