---
- name: Install required packages for libvirt
  ansible.builtin.dnf:
    name:
      - qemu-kvm
      - libvirt
      - libvirt-client
      - libvirt-daemon-config-network
      - virt-install
    state: present

- name: Start libvirt
  ansible.builtin.service:
    name: libvirtd
    state: started
    enabled: true

- name: Add user to libvirt group
  ansible.builtin.user:
    name: "{{ deploy_user_name }}"
    groups: libvirt
    append: true

- name: Ensure libvirt storage pool directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop: "{{ libvirt_storage_pools }}"
  loop_control:
    label: "{{ item.name }}"

- name: Define storage pools
  community.libvirt.virt_pool:
    command: define
    name: "{{ pool_name }}"
    xml: "{{ lookup('template', 'home-server/templates/pool_config.xml.j2') }}"
  loop: "{{ libvirt_storage_pools }}"
  loop_control:
    label: "{{ item.name }}"
  vars:
    pool_name: "{{ item.name }}"
    pool_path: "{{ item.path }}"

- name: Check if pools have already been defined and are active
  community.libvirt.virt_pool:
    command: facts
  register: pool_facts

- name: Determine which storage pools need to be defined
  ansible.builtin.set_fact:
    pools_to_define: "{{ (pools_to_define | default([])) + [item] }}"
  loop: "{{ libvirt_storage_pools }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.name not in (pool_facts.ansible_facts.ansible_libvirt_pools | default({}))

- name: Define missing storage pools
  community.libvirt.virt_pool:
    command: define
    name: "{{ pool_name }}"
    xml: "{{ lookup('template', 'home-server/templates/pool_config.xml.j2') }}"
  loop: "{{ pools_to_define | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  vars:
    pool_name: "{{ item.name }}"
    pool_path: "{{ item.path }}"

- name: Ensure storage pools are active
  community.libvirt.virt_pool:
    state: active
    name: "{{ item.name }}"
  loop: "{{ libvirt_storage_pools }}"
  loop_control:
    label: "{{ item.name }}"

- name: Set storage pools to autostart
  community.libvirt.virt_pool:
    autostart: true
    name: "{{ item.name }}"
  loop: "{{ libvirt_storage_pools }}"
  loop_control:
    label: "{{ item.name }}"