timezone: America/Detroit

username: mclaysen

sudoers_file_path: /etc/sudoers

security_ssh_config_path: /etc/ssh/sshd_config
security_sshd_name: sshd

security_ssh_port: 22
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "no"
security_sshd_state: started
security_ssh_restart_handler_state: restarted
security_ssh_allowed_users: 
  - "{{ username }}"
security_ssh_allowed_groups: []

security_sudoers_passwordless:
  - "{{ username }}"
security_sudoers_passworded: []

security_autoupdate_enabled: true
security_autoupdate_blacklist: []
security_autoupdate_additional_origins: []

nginx_worker_processes: auto
nginx_worker_connections: 768
nginx_gzip_enabled: true

certbot_email: me@mclaysen.com

domain: mclaysen.com

app_defaults:
  app_proxy_buffering: "off"
  app_max_body_size: 1M

sites:
  - app_name: photos
    app_domain: photos.mclaysen.com
    app_backend: http://192.168.86.200:20800
    settings:
      app_proxy_buffering: "on"
      app_max_body_size: 500M
    ssl_cert_path: /etc/letsencrypt/live/mclaysen.com/fullchain.pem
    ssl_key_path: /etc/letsencrypt/live/mclaysen.com/privkey.pem
  - app_name: homebridge
    app_domain: homebridge.mclaysen.com
    app_backend: http://192.168.86.108:8581
    ssl_cert_path: /etc/letsencrypt/live/mclaysen.com/fullchain.pem
    ssl_key_path: /etc/letsencrypt/live/mclaysen.com/privkey.pem
  - app_name: container-manager
    app_domain: container-manager.mclaysen.com
    app_backend: https://192.168.86.60:9443
    ssl_cert_path: /etc/letsencrypt/live/mclaysen.com/fullchain.pem
    ssl_key_path: /etc/letsencrypt/live/mclaysen.com/privkey.pem
  - app_name: nas2
    app_domain: nas2.mclaysen.com
    app_backend: https://192.168.86.103:5001
    ssl_cert_path: /etc/letsencrypt/live/mclaysen.com/fullchain.pem
    ssl_key_path: /etc/letsencrypt/live/mclaysen.com/privkey.pem
  - app_name: nas
    app_domain: nas.mclaysen.com
    app_backend: http://192.168.86.200
    ssl_cert_path: /etc/letsencrypt/live/mclaysen.com/fullchain.pem
    ssl_key_path: /etc/letsencrypt/live/mclaysen.com/privkey.pem
  - app_name: router
    app_domain: router.mclaysen.com
    app_backend: http://192.168.86.1
    ssl_cert_path: /etc/letsencrypt/live/mclaysen.com/fullchain.pem
    ssl_key_path: /etc/letsencrypt/live/mclaysen.com/privkey.pem
  - app_name: kvm
    app_domain: kvm.mclaysen.com
    app_backend: https://192.168.86.177:443
    ssl_cert_path: /etc/letsencrypt/live/mclaysen.com/fullchain.pem
    ssl_key_path: /etc/letsencrypt/live/mclaysen.com/privkey.pem
  - app_name: media-stats
    app_domain: media-stats.mclaysen.com
    app_backend: http://192.168.86.60:3000
    ssl_cert_path: /etc/letsencrypt/live/mclaysen.com/fullchain.pem
    ssl_key_path: /etc/letsencrypt/live/mclaysen.com/privkey.pem
  - app_name: hass
    app_domain: hass.mclaysen.com
    app_backend: https://192.168.86.78:8123
    ssl_cert_path: /etc/letsencrypt/live/mclaysen.com/fullchain.pem
    ssl_key_path: /etc/letsencrypt/live/mclaysen.com/privkey.pem
    custom: true
  - app_name: media
    app_domain: media.mclaysen.com
    app_backend: http://192.168.86.60:8096
    ssl_cert_path: /etc/letsencrypt/live/mclaysen.com/fullchain.pem
    ssl_key_path: /etc/letsencrypt/live/mclaysen.com/privkey.pem
    custom: true
    settings:
      app_max_body_size: 20M

  